baseURL = "https://hildejk.xyz/"
canonifyURLs = true
relativeURLs = false
languageCode = "en-us"
title = "Hildeberto Jardón-Kojakhmetov"

[params]
  tagline = ""
  affiliation = "University of Groningen"
  email = "h.jardon.kojakhmetov@rug.nl"
  github = ""
  scholar = "https://scholar.google.com/citations?user=g48MzEYAAAAJ&hl=en&oi=ao"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
